# Shared aliases (sourced by zsh and bash)

alias ip="ipconfig getifaddr en0"
alias cheat="~/dotfiles/bin/cheat"
alias zshconfig="nvim ~/dotfiles/.config/zsh/.zshrc"
alias bashconfig="nvim ~/dotfiles/.config/bash/bashrc"
alias zr="source ~/.zshrc"
alias br="source ~/.bashrc"
alias ohmyzsh="cd ~/.oh-my-zsh"
alias sshhome="cd ~/.ssh"
alias sshconfig="nvim ~/.ssh/config"
alias gitconfig="nvim ~/.config/git/config"

alias gitl="git lg"
alias gita="git add ."
alias gitc="cz commit"
alias gdf="git diff"
alias gc="git checkout"
alias gs="git status"
alias ga="git add"
alias gp="git push origin"
alias gpl="git pull origin"
alias gsp="git stash pop"
alias gst="git stash"
alias gsts="git_stash_show"
alias gstsm="git_stash_show_m"
alias gstd="git_stash_drop"
alias gstl="git stash list"
alias gsta="git_stash_apply"

alias dup="docker-compose up -d"
alias dbuild="docker-compose build"
alias dstop="docker stop"
alias dc="docker compose"

alias ls="eza --color=always --git --icons=always"
alias ll="eza -l --color=always --git --icons=always"
alias tree="eza --tree"
alias cat="bat"
alias fastfetch="fastfetch; printf '\n\n'"

alias loc="npx sloc --format cli-table --format-option head --exclude 'build|\.svg$\.xml' ./"
alias jsonencode="awk 'NF {sub(/\r/, \"\"); printf \"%s\\\\n\",\$0;}'"

alias mv="mv -vi"
alias cpv="rsync -avh --info=progress2"
alias cl="clear"
alias c="clear"

alias ..="cd .."
alias cd..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Theme aliases: reload is shell-specific (overridden in bashrc for bash)
alias theme-tokyo-night="starship preset tokyo-night -o ~/dotfiles/.config/starship/starship.toml --force && source ~/.zshrc"
alias theme-gruvbox="starship preset gruvbox-rainbow -o ~/dotfiles/.config/starship/starship.toml --force && source ~/.zshrc"
alias theme-jetpack="starship preset jetpack -o ~/dotfiles/.config/starship/starship.toml --force && source ~/.zshrc"
alias theme-nerdfont="starship preset nerd-font-symbols -o ~/dotfiles/.config/starship/starship.toml --force && source ~/.zshrc"
